### ISSUE TITLE
Broken str-replace()

### ISSUE THREAD

**Issue by rafegoldberg** [HugoGiraudel/SassyStrings#20]
@HugoGiraudel much ♡ for SassyStrings; really great set of utilities! But I've been running in to a bit of trouble when I try to use the `str-replace()` function. To illustrate, here's my SCSS:

```scss
// import sassystrings
.base {
  &__elem {
    content: str-replace( #{&}, '.', '#' );
  }
}
```

I'd expect this to replace any/all instances of a `.` character with a `#` so that the compiled CSS would read as follows:

```css
.base__elem {
  content: #base__elem; /* expected output */
}
```

Instead it's just spitting out the initial input string, as you can see below:

```css
.base__elem {
  content: .base__elem; /* actual output */
}
```

Any thoughts on what might be going wrong here or how to fix it? I'm going to take a closer look at your source code but I wanted to bring it to your attention. Thanks!

> **Note:**
> I should probably mention that I'm using [Sass V3.4.14](http://sass.logdown.com/posts/221239-sass-34-is-released) (for it's awesome new `&` selector capabilities) and the Ruby compiler, although using LibSass doesn't solve the issue either...
